service: chase

frameworkVersion: ">=1.1.0"

custom:
  bucket: syon-chase

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

package:
  exclude:
    - spec/**

functions:
  info:
    handler: handler.info
    events:
      - http:
          path: info
          method: get
  thumb:
    handler: handler.thumb
    events:
      - http:
          path: thumb
          method: get
    environment:
      BUCKET: ${self:custom.bucket}
